Update action.yml

diff --git a/.github/actions/susfs/action.yml b/.github/actions/susfs/action.yml
--- a/.github/actions/susfs/action.yml
+++ b/.github/actions/susfs/action.yml
@@ -111,17 +111,14 @@ runs:
       shell: bash
       working-directory: ${{ github.workspace }}/kernel/common
       run: |
-        SUPERCALL=$(find . -type f -path "*/common/drivers/kernelsu/supercall/supercall.c" | head -n 1)
-        ls -aR
-        if [ -n "$SUPERCALL" ]; then
-          if ! grep -q '#include <linux/syscalls.h>' "$SUPERCALL"; then
-            sed -i '/#include <linux\/fs.h>/a #include <linux/syscalls.h>' "$SUPERCALL"
-            echo "Added syscalls.h include to $SUPERCALL"
+        SUPERCALL="drivers/kernelsu/supercall/supercall.c"
+          if [ -f "$SUPERCALL" ]; then
+            if ! grep -q '#include <linux/syscalls.h>' "$SUPERCALL"; then
+              sed -i '/#include <linux\/fs.h>/a #include <linux/syscalls.h>' "$SUPERCALL"
+              echo "Added syscalls.h include to $SUPERCALL"
+            else
+              echo "syscalls.h already present"
+            fi
           else
-            echo "syscalls.h already present"
-          fi
-        else
-          echo "supercall.c not found"
-          exit 1
+            echo "supercall.c not found at expected path: $SUPERCALL"
         fi
-
